[package]
name = "tokio-trace-core"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
license = "MIT"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://tokio.rs"
description = """
Core primitives for tracing and diagnostics in asynchronous applications.
"""
categories = ["development-tools::debugging"]
keywords = ["logging", "tracing"]

[dependencies]
lazy_static = "1.0.0"
